### ISSUE TITLE
Expose RSQL Parser

### ISSUE THREAD

**Issue by binnie268** [mw-experts/rsql#25]
Hi @misticwonder,

I think this library is great and I am working on using it for a use case! Would it be possible to add RSQL Parser as part of the public api as well, for those that cannot use direct SQL but may be using an ORM?

Thanks! :)

**Comment by misticwonder** [comment]
Hi @binnie268 
Thank you for your feedback )
A have exported all tools you may need.
It is available in version 1.4.2.
Example of usage of parser you can find in one of this files:
- ./rsql-filter/rsql-filter
- ./rsql-to-sql-converter/rsql-to-sql-converter
